echo "-------------------------" >> /jmax/acme-challenge/test.log
echo "CERTBOT_DOMAIN:" >> /jmax/acme-challenge/test.log
echo $CERTBOT_DOMAIN >> /jmax/acme-challenge/test.log
echo "CERTBOT_VALIDATION:" >> /jmax/acme-challenge/test.log
echo $CERTBOT_VALIDATION >> /jmax/acme-challenge/test.log
echo "CERTBOT_TOKEN:" >> /jmax/acme-challenge/test.log
echo $CERTBOT_TOKEN >> /jmax/acme-challenge/test.log
echo "CERTBOT_REMAINING_CHALLENGES:" >> /jmax/acme-challenge/test.log
echo $CERTBOT_REMAINING_CHALLENGES >> /jmax/acme-challenge/test.log
echo "CERTBOT_ALL_DOMAINS:" >> /jmax/acme-challenge/test.log
echo $CERTBOT_ALL_DOMAINS >> /jmax/acme-challenge/test.log